### PR TITLE
Handle validation exceptions.

### LINKED ISSUE #121: Uncaught exception exit code coherency
Apparently, when the `cfn-lint` cli executable encounters an uncaught exception during the `validate` command, it logs the exception's stack trace and returns a `0` exit code, implying that the program exited succesfully. However, at least from my limited point of view, this should not be the case due to the fact that it was actually unable to parse and determine the template's validity and therefore it should return a non-zero exit code, perhaps even a different one than for the invalid template scenario.

Steps to reproduce:
1) Create a `test.yaml` file that triggers an exception, perhaps with the following contents:
```
Resources:
  MyBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      Tags: null
```
2) Attempt to validate the file:
`cfn-lint validate test.yaml`
3) Observe the output and exit code:
[validate.log](https://github.com/martysweet/cfn-lint/files/1855988/validate.log)

Expected: A non-zero exit code.

### PR DESCRIPTION
**Pull request by RazzM13**
Fixed #121 and #122. Catches exceptions thrown in template validation and logs `Unable to parse template!` to `stdout`, if `--verbose` flag provided then logs the exception to `stderr`. In both cases the exit code is `1`.

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -74,7 +75,17 @@ if(firstArg == "validate"){
         guessParameters
     };
 
-    let result = validator.validateFile(secondArg, options);
+    let result = Object();
+    try {
+      result = validator.validateFile(secondArg, options);
+    } catch(err) {
+      console.log('Unable to parse template!');
```
Comment (martysweet) [inline src/index.ts]: I think something to spur the user on to resolve the issue would be helpful here.

"Unable to parse template! Is the template formatted correctly?"
"Unable to parse template! Does the path exist?"
"Unable to parse template! Use --verbose for more information."

Probably the last one is most useful.

Additionally, as we are now catching the file not found, it might be nice to return this as a separate error, so this parsing error is the last case "I've run into terrible difficulty" message, as opposed to something that could be encountered due to a typo.

Comment (RazzM13) [reply src/index.ts]: Sounds very nice. I believe that from a UX quality perspective the most specific messages are best for users however, they tend to become tedious to maintain therefore I'd like to lean on a combination of 3 and 2 implying that perhaps we should provide sufficiently specific messages for common scenarios such as invalid path and at the same time provide a broad catch-all type message for not really expected exceptions :)  ... then again it's just a thought I think you have more experience with this project and perhaps see things more clearer than I do.

Comment (martysweet) [reply src/index.ts]: I think

`Unable to parse template! Use --verbose for more information.` would work best for a general fall-through then.

Then we just need to add some extra logic to check if a path exists and return an error nicely.

File: src/index.ts [hunk 2]
```diff
@@ -74,7 +75,28 @@ if(firstArg == "validate"){
...
+      result = validator.validateFile(secondArg, options);
+    } catch(err) {
+      let error: string = function(msg: string, errors: any) {
+        for (let error of Object.keys(errors)) {
+          if (RegExp(error).test(msg)) {
+            return errors[error];
+          }
+        }
+        return errors[''];
+      }(err.message, {
```
[the remark this answers is not in the document]
Comment (RazzM13) [reply src/index.ts]: I'm not sure... should it?

**Comment by RazzM13** [comment]
Trully sorry for not catching this sooner but I was expecting the build to fail due to the different error handling messages, which I would have fixed after you've approved the last change,  but certainly not in that way. 
I believe that the problem is that the `safer-buffer` polyfill did not mimick the real `Buffer` API as it should have and it was missing the constructor function which is why `instanceof` was failling; I've changed the polyfill in PR #130 and now it should be working.

File: src/index.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (martysweet) [reply src/index.ts]: Apparently not :+1:

**Comment by martysweet** [comment]
No worries

LGTM, just those tests to cleanup, ensuring the `--verbose` flag is throwing out a stack trace.

**Comment by RazzM13** [comment]
I've just updated the tests with the new error messages and I've had to diverge from the non-existing file exception to a general parsing exception (i.e. `invalid_yaml.yaml`) due to the new behavior for that case. Also, when checking the `--verbose` functionality, I'm just trying to locate the specific exception message within `stderr` and not really parsing it as an exception that has a message and a strack trace; hoping this suffices if not, then perhaps you could direct me to an easy way of doing just that :)

**Comment by martysweet** [comment]
Good stuff!
